development:
  adapter: postgis
  username: postgres
  password: postgres
  database: planting_calendar_dev
  encoding: utf8
  host: 127.0.0.1

test: &test
  adapter: postgis
  username: postgres
  password: postgres
  database: planting_calendar_test
  encoding: utf8
  host: 127.0.0.1

cucumber:
  <<: *test
